### PR TITLE
Duplication of condition

### PR DESCRIPTION
**Pull request by peter-gribanov**
$values must be array but can be empty

### CODE REVIEW

**Comment by peter-gribanov** [comment]
PS: Where can I report bugs?

**Comment by tomatolog** [comment]
you could report bug at mantis here http://sphinxsearch.com/bugs

**Comment by peter-gribanov** [comment]
> you could report bug at mantis here http://sphinxsearch.com/bugs

Thanks

**Comment by adriannuta** [comment]
Fixed at  deb64e2

**Pull request closed without merging**
